name: Release
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: make test
  
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: golangci/golangci-lint-action@v8

  release:
    needs:
      - test
      - linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: make install-release-tool new-patch-release
